language: java

sudo: false

matrix:
  include:
    - os: linux
      dist: precise
      jdk: oraclejdk7
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: oraclejdk9

after_success:
  - mvn clean test jacoco:report coveralls:report
